(defun example11 (&optional (file #P"ex5.pdf"))
  (pdf:with-document ()
    (pdf:with-page ()
      (pdf:with-outline-level ("Example" (pdf:register-page-reference))
	(let ((helvetica (pdf:get-font "Helvetica")))
	  (pdf:in-text-mode
	   (pdf:set-font helvetica 14.0)
	   (pdf:move-text 100 700)
	   (pdf:show-text "cl-pdf: Example 1")
           (pdf:move-text 0 -20)
	   (pdf:show-text "cl-pdf: Example 2")
           (pdf:move-text 0 -20)
	   (pdf:show-text "cl-pdf: Example 3")))))	  
	  (pdf:write-document file)))
